name:  curl CiCD
on:
  workflow_dispatch:
    branches:
      - master
jobs:
  trigger_workflow:
    runs-on: ubuntu-latest

    steps:

      - name: Echo Workflow name

        shell: bash

        run: |

          echo "I am Workflow of Parent REPO"

      - name: Trigger child repo 

        uses: rshop/trigger-workflow-action@v1
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: 'dittojoseph/scripted-pipeline-demo'
          workflowId: deploy.yaml
          branch: test
