name: Trigger

on:
  workflow_dispatch:
    inputs:
      repository:  
        description: 'scripted-pipeline-demoscripted-pipeline-demo'
        required: true
      workflow: 
        description: 'deploy.yaml'
        required: true
      ref:         
        description: 'master'
        required: true

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Workflow
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # Personal Access Token with workflow scope
        repository: ${{ github.event.inputs.repository }}
        workflow: ${{ github.event.inputs.workflow }}
        ref: ${{ github.event.inputs.ref }}
