name:  API CI/CD
on:
  workflow_dispatch:
    branches:
      - master
jobs:
    build:
    
      runs-on: ubuntu-latest
      steps:
        - uses: actions/github-script@v7
          with:
            github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            await github.rest.actions.createworkflowDispatch({

              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['Triage']
            })
