name:  API CI/CD
on:
  workflow_dispatch:
    branches:
      - master
jobs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            await github.rest.actions.createworkflowDispatch({
                owner: 'dittojoseph',
                repo: 'scripted-pipeline-demo',
                workflow_id: 'deploy.yaml',
                ref: 'master'
            }) 
