name:  API CICD
on:
  workflow_dispatch:
    branches:
      - master
jobs:
  trigger_workflow:
    runs-on: ubuntu-latest

    steps:
    run: |
    curl -L \
   -X POST \
   -H "Accept: application/vnd.github+json" \
   -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
   -H "X-GitHub-Api-Version: 2022-11-28" \
   https://api.github.com/repos/dittojoseph/scripted-pipeline-demo/actions/workflows/deploy.yaml/dispatches \

   -d '{"ref":"master"}' 
