name:  Parent CI?CD
on:
  workflow_dispatch:
    branches:
      - master
jobs:
  trigger_workflow:
    runs-on: ubuntu-latest

    steps:

      - name: Echo Workflow name

        shell: bash

        run: |

          echo "I am Workflow of Parent REPO"

      - name: Trigger workflow file
        uses: actions/github-script@v6
        with:
        github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        script: |
            await github.rest.actions.createworkflowDispatch({
                owner: 'dittojoseph',
                repo: 'scripted-pipeline-demo',
                workflow_id: 'deploy.yml',
                ref: 'master'
            }) 
